### ISSUE TITLE
pdf_decribe rejects PDF that Adobe Reader accepts. ParseFloat

### ISSUE THREAD

**Issue by peterwilliams97** [unidoc/unidoc#103]
strconv.ParseFloat: parsing "0.00-34120734": invalid syntax
[Deep Neural Networks for YouTube Recommendations.pdf](https://github.com/unidoc/unidoc/files/1199214/Deep.Neural.Networks.for.YouTube.Recommendations.pdf)

**Comment by gunnsth** [comment]
I ran the file through with gs, which complains about an unknown operator
Page 5
   **** Error: Unknown operator: '0.00-34120734', processed as number, value: 0.0
                Output may be incorrect.

The problem is within a content stream, where
q
1.0
0
0
1.0
234.66498
0.00-34120734
cm

appears..   Clearly cm can only have 6 inputs, so it appears that this extra string is there although it is not really clear whether the last number should be only 0.00.

I am uncertain how to handle this.  This appears like a pretty serious error.  In many cases I would like this to fail.

Of course we are already doing a lot of dancing around PDF syntax errors, so this might be just another one of those.

What do you think?

**Comment by peterwilliams97** [comment]
The following code seems to give the same result as gs and pdftops

```
if isFloat {
		fVal, err := strconv.ParseFloat(numStr, 64)
		if err != nil {
			common.Log.Error("Error parsing number %q err=%v. Using 0.0. Output may be incorrect", numStr, err)
			fVal = 0.0
			err = nil
		}
		o := PdfObjectFloat(fVal)
```
