### ISSUE TITLE
Support for adding links to text

### ISSUE THREAD

**Issue by gnewton** [unidoc/unidoc#135]
I could not see anywhere in the  docs or API that this was supported: I would like to be able to add a hyperlink to an existing piece of text in the document.

**Comment by gunnsth** [comment]
Can you give me an example of a PDF with a hyperlink?  In many cases the PDF viewer automatically converts urls of typical format into links.  Otherwise you might be referring to special annotations, i.e. a Link annotation.

These need to be specified by a certain rectangular region around the area (text or image for example as specified by coordinates) and an action which can refer to the URL (URI) to go to.

There is not currently an easy way to add these Link annotations when using the creator, but the model for the Link annotation is defined in the models.go.  More information can be found in the PDF standard.

**Comment by gnewton** [comment]
Here is an example: the clickable url at the bottom of Page 1 of this PDF document: http://mirror.its.dal.ca/ctan/macros/latex/contrib/hyperref/doc/manual.pdf

I will take a look at the Link annotations and how that might be used.
Thanks!
Great library, BTW!

**Comment by gnewton** [comment]
Yes, I found it on p394 of http://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf

**Comment by gunnsth** [comment]
Closed by #262
