### ISSUE TITLE
Reader failure if page Resources are declared indirectly

### ISSUE THREAD

**Issue by quetz** [unidoc/unidoc#151]
It happens because `PdfPage.getResources` lacks indirect object resolving when trying to get to `Resources` dict.

PDF file for testing is here: https://github.com/quetz/unidoc/releases/download/151/151.pdf

PR: https://github.com/unidoc/unidoc/pull/152

**Comment by quetz** [comment]
As as side note, can you please explain the difference between `PdfObjectReference` and `PdfIndirectObject`. At first glance its basically the same thing (with equal representation in file), but having different functions to dereference those.

There's `TraceToDirectObject` for `PdfIndirectObject` and `PdfReader.traceToObject` for `PdfObjectReference`. This is pretty confusing at first glance, but maybe there's some idea behind it?

Are there any drawbacks in removing `PdfObjectReference` altogether and using `PdfIndirectObject` instead?

**Comment by gunnsth** [comment]
@quetz The reference and indirect objects are two separate objects as per the PDF standard.  The reference object is just a pointer to an indirect object.  For example, a reference to indirect object number 10 would be "10 0 R" in PDF.   Whereas the indirect object would start with "10 0 obj ..... content ... endobj".  In many cases when we work with PDFs we only work with parts of the PDF and never have to resolve the references. That is why using reference objects and only resolving on an as-needed basis is computationally efficient.

The unexported traceToObject has access to the cross reference table and can resolve references (i.e. read and retrieve entire objects from the PDF.  It is mostly used internally, when the objects have not been resolved.  When we start reading the PDF, starting from the trailer object, and then moving onto the catalog, pages etc, there is a lot of reference objects that need to be resolved.  The function traverseObjectData goes through objects recursively and converts references to indirect objects, i.e. looks up the reference and replaces with the indirect object (or a pointer to it more accurately as once we read an object, it is cached).

The exported TraceToDirectObject is just for convenience.  If a direct object is wrapped inside an indirect object, it simply unwraps it and returns the direct object.  It cannot resolve references (and does not have access to the cross references or PDF file descriptor).

I do not think that the PdfObjectReference can be removed.  Otherwise would need to load the objects immediately when encountering a reference during parsing, which could lead to overhead (if those objects do not end up being needed).

Hope that helps. This could probably be better explained, but at least it should give some idea on how it works.  If you have any suggestions for improvement, let me know :).

**Comment by quetz** [comment]
Thanks alot! It makes much more sense now.

> The reference and indirect objects are two separate objects as per the PDF standard. The reference object is just a pointer to an indirect object. For example, a reference to indirect object number 10 would be "10 0 R" in PDF. Whereas the indirect object would start with "10 0 obj ..... content ... endobj"

That said, reference and indirect objects should have different `DefaultWriteString` implementation. Former has to output `10 0 R` and latter `10 0 obj ... endobj` while in source code it is not true for `PdfIndirectObject` - https://github.com/unidoc/unidoc/blob/master/pdf/core/primitives.go#L524
Is it intended?

What do you think about idea of automatically resolving references down to object when doing `.Get` from a dict? Right now most dict accesses are followed by code like this:
```
	if obj := d.Get("LastModified"); obj != nil {
		var err error
		obj, err = reader.traceToObject(obj)
		if err != nil {
			return nil, err
		}
		strObj, ok := TraceToDirectObject(obj).(*PdfObjectString)
```
That would reduce some boilerplate and possibly remove some bugs when we assume object but get indirect object (reference) instead. Or maybe at least we could combine this 2-step tracing into 1-step because that's what we usually want.

**Comment by gunnsth** [comment]
That would mean that the dictionary would need to be able to have access to the PdfReader and also that Get could fail, i.e. Get would need to return (PdfObject, error) as the reference lookup can fail.

Array objects can also hold references, so something similar needed when accessing those.

Indirect objects can also hold references, e.g.
10 0 obj
1 0 R
endobj

Typically unfolded with TraceToDirectObject or the traceToObject.

These kinds of changes can only be done in a major release.  But good to start thinking about it now.  I think many of your points are good and could lead to simplified and more readable code.  I think the basic object handling can be improved.

Might be good to start playing around with these in a new branch.

**Comment by gunnsth** [comment]
@quetz Regarding the DefaultWriteString implementation for PdfObjectIndirect vs PdfObjectReference, The DefaultWriteString method never outputs the "n m obj ... endobj" syntax, that is done elsewhere, in
https://github.com/unidoc/unidoc/blob/master/pdf/model/writer.go#L436
where all the indirect objects sequentially.

When the DefaultWriteString method is called, then it just means that it should write out a reference to that object.

**Comment by gunnsth** [comment]
@quetz The shorter syntax

> strObj, ok := TraceToDirectObject(obj).(*PdfObjectString)

is actually quite safe to use and easy.  I have been using this syntax more lately.

**Comment by quetz** [comment]
> That would mean that the dictionary would need to be able to have access to the PdfReader and also that Get could fail, i.e. Get would need to return (PdfObject, error) as the reference lookup can fail.

It is possible to have it return `nil` if object resolving failed (this way you can use type assertion on return value right away). But need to access to PdfReader is unfortunate. From the other side, having reader available to all PdfObjects allows for interesting optimisations (where parts of PDF are loaded on the fly as needed). For example at the moment counting pages in PDF involves instantiating all page objects (with everything inside) and only then counting those page objects.

Speaking of other containers (arrays) - yeah, that'd need automatic dereferencing also.

Is it possible to use your test-suite (PDFs) while playing with these changes?

> The shorter syntax
strObj, ok := TraceToDirectObject(obj).(*PdfObjectString)

This should work if PdfReference is already resolved to PdfIndirectObject, but would not work on PdfReference (if i understand it correctly)

**Comment by gunnsth** [comment]
Yes, this could lead to a significant optimization.  Effectively would resolve #128 

Definitely, we would need to test this properly.  First should be fine to test with a test suite and a few files in a new branch.  Then we can test on a larger corpus and ensure that there is no regression.  Typically would test this with a pass-through (identity) test, i.e. read in and write out and use ghostscript to check for correctness.  Sure, it would be possible.

Correct regarding the last point.

**Comment by gunnsth** [comment]
@quetz I suggest we create a new ticket for this task as it is getting somewhat far from the original topic.

**Comment by quetz** [comment]
> I suggest we create a new ticket for this task as it is getting somewhat far from the original topic.
Sounds good.
