### ISSUE TITLE
Endless loop, resulting in out of memory crash

### ISSUE THREAD

**Issue by Kleissner** [unidoc/unidoc#176]
There is a bug in `cstreamParser.ExtractText` (or a sub-function) where it's running in an endless loop on a certain PDF (attached to this issue). It will allocate more and more memory and then eventually crash with "out of memory" panic.

I tested it with the `pdf_extract_text` program from https://github.com/unidoc/unidoc-examples/blob/master/pdf/text/pdf_extract_text.go

```
pdf_extract_text.exe 93140dc0-ab07-4b5c-bc84-885bbbe46647.pdf
```

On this PDF file: [93140dc0-ab07-4b5c-bc84-885bbbe46647.pdf](https://github.com/unidoc/unidoc/files/2275934/93140dc0-ab07-4b5c-bc84-885bbbe46647.pdf)

It will occur when extracting the text from page 106 of the PDF file.

**Comment by gunnsth** [comment]
Looking into this, this happens because of the content stream being invalid or corrupted. The faulty part looks like:
```
T*(consumed daily. Recent reseaoialcohong oorcre5olver\^M.8r5Tj^M6r5ao.lab o th(y which)Tj^M1.0833 TL duration1uonsiderable bleedin\foy bestd distdoltCo5rog mBlng)Tj^M0rable bleeded)Tj^M1.0833 TL
```
In trace mode, unidoc loads the first part as a single string (although containing multiple operands). Likely some kind of memory corruption or something, unfortunately containing an additional '('

```
[TRACE]  parser.go:46 (consumed daily. Recent reseaoialcohong oorcre5olver.8r5Tj^M6r5ao.lab o th(y which)Tj^M1.0833 TL duration1uonsiderable bleedin^Loy bestd distdoltCo5ro
g mBlng)
[TRACE]  parser.go:46 Peek string: Tj
[TRACE]  parser.go:46 ->Operand or bool?
[TRACE]  parser.go:46 cont Peek str: Tj^M0r
[TRACE]  parser.go:46 Peek string: 0r
[TRACE]  parser.go:46 ->Number!
[TRACE]  parser.go:557 Parsing number ""
[TRACE]  parser.go:557 Parsing number "0"
[TRACE]  parser.go:46 Peek string: ra
[TRACE]  parser.go:46 ->Operand or bool?
[TRACE]  parser.go:46 cont Peek str: rable
[TRACE]  parser.go:46 Peek string: bl
[TRACE]  parser.go:46 ->Operand or bool?
[TRACE]  parser.go:46 cont Peek str: bleed
[TRACE]  parser.go:46 Peek string: )T
[TRACE]  parser.go:46 ->Operand or bool?
[TRACE]  parser.go:46 cont Peek str: )Tj^M1
[TRACE]  parser.go:46 Peek string: )T
[TRACE]  parser.go:46 ->Operand or bool?
[TRACE]  parser.go:46 cont Peek str: )Tj^M1
[TRACE]  parser.go:46 Peek string: )T
[TRACE]  parser.go:46 ->Operand or bool?
[TRACE]  parser.go:46 cont Peek str: )Tj^M1
... stuck in endless loop here
```
The problem was when it encountered the ")" where it was expecting an operand.
I have fixed it so it will return an error instead.

Unfortunately we do not have a way of repairing content streams at this time. Note that with such corruption you would never be able to get everything 100% correct.  Programs such as ghostscript also fail on this file with an error
```
   **** Error reading a content stream. The page may be incomplete.
   **** Illegal; nested BT operator (inside a gsave) detected.
   **** File did not complete the page properly and may be damaged.
```
However, I believe in this case, if there was a recovery mode, it could probably get 90-95% of things correct.  We may offer a recovery mode later, but for now at least it simply errors out and you can choose to ignore the error and continue processing the following pages.

The fix is now available in branch extracttext-endlessloop-fix, we will be reviewing and merging this into master shortly.
