### ISSUE TITLE
Colorspace parsing fails if name is IObject

### ISSUE THREAD

**Issue by quetz** [unidoc/unidoc#188]
If colorspace is specified as array and first element of array is IObject pointing at CS name parsing fails (yet another TraceToDirectObject missing)

There are two PRs:
Simple fix (just add missing TraceToDirectObject): https://github.com/unidoc/unidoc/pull/186
Rewrite/simplify parsing logic while also fixing this problem (tried to follow PDF spec closely): https://github.com/unidoc/unidoc/pull/187

 I pretty much sure I'm missing something in #187 so could you please explain what? (It works on our document corpus)

**Comment by gunnsth** [comment]
I would go with the simple fix #186.  (and will add a fix based on your PR).

Main difference in #187 I see you are calling the New... methods on the array object rather than the containing object. (indirect obj), but I don't believe that matters here.  In some cases we want to call with the containing object (for caching purposes), but not used here.

If rewriting the parsing logic, I think it would be nice to use more type switching statements, as it makes the code easier to read.

Note that in v3, with the recommended core.GetArray, ...., core.GetType methods, the TraceToDirect will be less needed.

**Comment by quetz** [comment]
Main idea for #187 was to use TraceToDirect as first step and avoid checking for IndirectObjects later on in the middle of function. How are you planning to use type switch statements? All constants we match on are simple strings (like "DeviceRGB" or "ICCBased") and they do not have separate types. 
Oh and by the way, is there any changelog for v3?

**Comment by gunnsth** [comment]
@quetz  Can you verify that PR #245 fixes the issue?  And if you could run against your bigger corpus as well would be great for validation.

**Comment by quetz** [comment]
@gunnsth yep, that works. thanks!
