### ISSUE TITLE
Support incremental updates when writing out PDF (append mode)

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unidoc#197]
# Current status
Currently PdfWriter always writes out only the necessary objects, i.e. objects that are referenced, and in the order they are found when traversing the PDF object hierarchy.

PDF has support for making incremental changes where the original PDF is unmodified, and only the changes are written out, with a new xref table.  

This is an important feature for digital signatures, as it allows the hashed data to stay in tact, when modifying the PDF, such as happens if a document is signed by multiple parties.

# Requirements

We need to be able to pass an original PDF to the writer prior to writing out and setting append mode, e.g.
```go
writer.SetIncrementalUpdates(srcReader)  // Pass the PdfReader of an original document as argument.
```
This would enable the incremental mode, and use the PDF loaded in `srcReader` as the source file.

# References
- Section 7.5.6 Incremental updates in PDF32000_2008 p. 52.

**Comment by iamacarpet** [comment]
@gunnsth does this mean that as the name suggests, the original document remains untouched, but with data at the end of the file that tells it to be ignored in favor of the new changes?

Or does it pass everything from the original document through to the writer, but the new document would have the changes in place of the old data, e.g. the AcroForm definition missing from the new file entirely, replaced by the filled in data after a flatten operation, but otherwise the same?

**Comment by gunnsth** [comment]
@iamacarpet  The former, i.e. original document untouched (entirely same hash over that byte range).  The addition makes a new cross references table and can change the document structure as needed, although all original objects remain in the file (even if not used).

**Comment by iamacarpet** [comment]
Would it be possible to have a middle ground of the latter in addition to this?

That's the default behavior when we've been using iText, to pass the source PDF reader object to the writer so everything starts out the same as the source, then just make & save modifications to the bits we touch as part of the manipulation, leaving the rest untouched.

I see your use case with the append mode for preserving signatures, but in our case we don't really want the AcroForms definition to be present in the end document while preserving the other document elements that seem to be stripped at the moment.

**Comment by gunnsth** [comment]
@iamacarpet Thanks for your input.  However, it is not part of this ticket and would require creating a more specific task as this can be accomplished in more than one way (e.g. just specifying what to preserve).

**Comment by a5i** [comment]
I create a prototype which tries to implement simple API to an incremental update existing PDF document ( PDF32000_2008 7.5.6 Incremental Updates, page 44). Pull request https://github.com/unidoc/unidoc/pull/253 

Example API
```go
// AddPages adds pages to end of the source Pdf.
func (a *PdfAppender) AddPages(pages ...*PdfPage) { }
// MergePageWith appends page content to source Pdf file page content.
func (a *PdfAppender) MergePageWith(pageNum int, page *PdfPage) error { }
// ReplacePage replaces the original page to a new page.
func (a *PdfAppender) ReplacePage(pageNum int, page *PdfPage) error { }
```

I have a lot of problems to track which Pdf object was changed.
For example when I modify AcroForm. I add a new field I must create a new AcroForm Pdf indirect object with a new dictionary but the new dictionary has to have old fields ref and one new. I need to append only new objects. So I can't use PdfAcroForm structure.

There is some code shows API idea.
```go
////////////////////
// Test case 2:
// filled.pdf is a form that has been signed by 1 party.
// and we need to fill out some fields as well.

filled, _ := os.Open("filled.pdf")

pa, _ := NewPdfAppender(filled)

form := pa.AcroForm

signatureField, wa := createSignatureField() // Create a *PdfField
form.Fields = append(form.Fields, signatureField)

p := pa.GetPage(1) // Assume signature is to be placed on page 1.
wa.Page = p
p.Annotations = append(p.Annotations, p)

filled.ReplacePage(p)
filled.ReplaceForm(form)

filled.WriteFile("signed.pdf") // signed by party 2.
```
This API is very hard to implement. I need to have something like immutable objects/structures or deep Pdf tree comparison because I need to append only changed Pdf objects.
Another case, when I add a new page with forms to appender from other PdfReader I need to merge AcroForm but I didn't implement it yet.

An another way, it's explicit mark PdfObject changes something like:
```go
sReader.Map(func (ctx PdfObjectCtx) error {
 ctx.UpdateObj(...)
 // or ctx.Delete()
 return nil
})
```

I think about the next use cases:
 - change content in one page
 - change page rotation
 - add a new page
 - remove a page
 - replace a page
 - merge a page with another page
 - add an annotation to the page
 - add a field to AcroForm
 - merge, add a new page with AcroForm from another PdfReader

What do you think?

**Comment by gunnsth** [comment]
Here are my thoughts (no conclusion yet).

My initial thought: I believe immutable objects could be expensive for this use case as it would require a lot of expensive copying (and memory use).  Please correct me if I am wrong. This would also require changing the access to models such that the fields can not be manipulated directly, providing Setters, which would return a modified copy of the object (for each time it was changed).

Possibly immutable objects that only make copies of the skeleton (not deep copy), would be OK.

A deep comparison of the entire PDF structure would be computationally intensive and somewhat wasteful as well.  For example, if we think about adding a signature to a single page of a 1000 page document.  Should be simply replacing the annotations for that page (potentially copying the page indirect object and changing out the Annotations), as well as appending updating the references, appending the field and updated form.

What about deep tree comparison on only marked indirect objects? 
```go
func (a *PdfAppender) MarkAsChanged(orig, modified PdfModel)
```
where `orig` is the original PdfModel and `modified` the updated one? Of course need to make sure that the `orig` is truly the unmodified object. It would be up to the user to ensure that this is the case (unless we can figure out a better way).

The routine would do a deep scan through `obj` and construct a map of full list of objects that require to be added (appended).

This would presumable allow something like
```go
filled, _ := os.Open("filled.pdf")
origPdf, _ := NewPdfReader(filled)

pa, _ := NewPdfAppender(origPdf)

signatureField, wa := createSignatureField() // Create a *PdfField
form.Fields = append(form.Fields, signatureField)

p := origPdf.GetPage(1) // Assume signature is to be placed on page 1.
wa.Page = p
p.Annotations = append(p.Annotations, p)

pa.MarkAsChanged(origPdf.AcroForm, form.AcroForm)
pa.MarkAsChanged(origPdf.GetPage(1), p)

pa.WriteFile("signed.pdf") // signed by party 2.
```

To avoid changes to the objects we could add an immutable reader type
```go
type ImmutableReader struct {
  reader *PdfReader
}
func NewImmutableReader(pdfPath string) (ImmutableReader, error) { ..}

// GetPage returns an immutable copy of PDF page `pnum`.
func (ir ImmutableReader) GetPage() (PdfPage, error) {
  p, _ := ir.reader.GetPage()
  // Returns a "shallow" copy.
  return *p, nil
}
// You get the idea...
```
Then the could would change to
```go
filled, _ := os.Open("filled.pdf")
origPdf, _ := NewImmutableReader(filled)

pa, _ := NewPdfAppender(origPdf)

signatureField, wa := createSignatureField() // Create a *PdfField
form.Fields = append(form.Fields, signatureField)

p := origPdf.GetPage(1) // Assume signature is to be placed on page 1.
wa.Page = p
p.Annotations = append(p.Annotations, p)

pa.MarkAsChanged(origPdf.AcroForm, form.AcroForm)
pa.MarkAsChanged(origPdf.GetPage(1), p)

pa.WriteFile("signed.pdf") // signed by party 2.
```

These are my thoughts at the moment. Would be good to get counter arguments and other input.

**Comment by peterwilliams97** [comment]
I looked in a bunch of signed PDFs that I downloaded from the internet and they all seemed to do simple appending.

`%%EOF
....
27 0 obj
...
%%EOF
`

**Comment by a5i** [comment]
@gunnsth I like the ImmutableReader idea. It looks clean and understandable.
I think ImmutableReader should reread Page or AcroForm from io.ReadSeeker when we use `originPdf.GetPage(num)` or `originPdf.GetAcroForm()`. We are able not to load all pages by PdfReader but load only needed pages in this case.

**Comment by dennwc** [comment]
Comparing the trees is definitely not an option. This will slow things down without any benefit and won't scale to large documents.

And I like the general idea of the `ImmutableReader`, but it's not that intuitive to let users mark changed objects by hand.

It would be nice to have all forms/pages/documents/etc with unexported fields and expose everything via getters/setters. In this case, objects can track changes on their own and either append or rewrite the document directly. But the API surface is pretty large. I hardly imagine writing a separate setter for each field in this type to track changes.

Thus, I think the only way to achieve immutability here is to make `PdfObject` an interface and always keep a reference to a document, so `PdfObject` can only be created in the context of a document. And then implement a `Page` model on top, that will call setters/getters on the `PdfObject`. To batch updates, a separate `Freeze`/`Commit`/`Flush` method can be added to the document/object. Since everything is hidden under an interface this will allow appending changes or rewriting objects in-place, depending on which mode the document was opened.

You can think of it as separating a `PdfObject` and its storage from the model. By doing this, only the lowest level will know about appending and everything else will work automatically regardless of how complex an operation is.

This might sound good, but the amount of changes is massive. Maybe this specific implementation can wait until `v4` and for now we can choose something that requires to explicitly mark changed objects.

**Comment by a5i** [comment]
@gunnsth Yes, we can close this issue.
