### ISSUE TITLE
Variable declaration styling guidelines

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unidoc#241]
A few cases have come up for discussion during code reviews. It is desired to define the recommended practice for consistency and readability.

It is a question of type and value explicitness vs readability.  There does not seem to be a true consensus on this.

# Examples

1. int, default value 0
```go
var start int
var numRounds int

// or

start := 0
numRounds := 0
```

2. string, default empty
```go
text := ""

// or

var text string
```

3. int, declaration for loop
```go
i := 0
for i < l { ... }

// or

var i
for i < l { ... }
```

4. numeric values with initial values 0.0 (float64) and -1 (int)
```go
var linewidth float64
var lastwidth float64
lastbreakindex := -1

// or
linewidth := 0.0
lastwidth := 0.0
lastbreakindex := -1

// or
linewidth := float64(0.0)
lastwidth := float64(0.0)
lastbreakindex := int(-1)
```

5. custom type initialized
```go
alignment := quaddingLeft

// or

var alignment quadding = quaddingLeft

// or

alignment := quadding(quaddingLeft)
```

6. float64 used in calculation/algorithm
```go
ty := 0.0
if condition {
    ty += 2.0
}

// or
var ty float64
if condition {
   ty += 2.0
}
```

7. bool value with false default
```go
isMultiline := false  // default condition
if condition {
    isMultiline = true
}

// or

var isMultiline bool
if condition {
  isMultiline = true
```

8. bool value with true default
```go
isMultiline := true   
if condition {
    isMultiline = false
}

// or

var isMultiline bool = true
if condition {
  isMultiline = false
```

# Proposal
None yet.  Looking to gather more comments before coming up with the proposal.
Please leave your comments with more examples or views.

We are looking for a consensus that is consistent, explicit and reads well.

**Comment by dennwc** [comment]
I usually follow this set of rules:
1) Always merge `var` blocks:
```golang
var (
 a int
 b bool
)
// instead of:
var a int
var b bool
```
2) Do not initialize zero slices or structs, define a `var` instead:
```golang
var (
  s []string
  c custom
)
// instead of
s := []string{}
c := custom{}
```
3) Use type inference where possible, but don't infer `float`:
```golang
var (
  a = 0
  b = false
  c = x
  // exception
  v float64 = 3
)
```
4) If there are more than 2-3 variables, prefer a `var` block instead of `:=`
```golang
var (
  a = 0
  b float64
  c custom
  d []string
)
// instead of
a := 0
b := 0.0
c := custom{}
d := []string{}
```
Also [this](https://github.com/golang/go/wiki/CodeReviewComments) might be relevant.

**Comment by peterwilliams97** [comment]
These are hard questions. I hoped the Go style guide would tell us what to do but I couldn't find anything. Does anyone here know where we can ask the Go authors what to do?

I find this natural to read
ty := 0.0
if condition {
    ty += 2.0
}

while this make me think "What is the float64 default?" even though it is obviously 0.0 

var ty  float64
if condition {
    ty += 2.0
}

**Comment by adrg** [comment]
My two cents:

#### Case 1
```
var start int
var numRounds int
```
I prefer this version because the zero value is obvious. However, in the other case, the type of the
variable may not be.

#### Case 2
```
var text string
```

Again, the zero value is obvious and also specified in the language documentation.

#### Case 3
```
	var i int
	for i < l {
                i++
	}
```

But only if I need the i variable after the for loop. Otherwise:

```
	for i := 0; i < l; i++ {
	}
```

#### Case 4
```
var linewidth float64
var lastwidth float64

lastbreakindex := -1
```

I would use an empty line here in order to make the code look better. I would use this syntax just to pass golint. I don't really like that I have to know that the type of lastbreakindex is an int here.

However, if I want another type for the lastbreakindex variable (e.g. int64):
```
var linewidth float64
var lastwidth float64
var lastbreakindex int64 = -1
```

golint complains only when the inferred variable type is explicitly written. This would not pass golint:
```
// Sidenote: lastbreakindex should really be named lastBreakIndex.
var lastbreakindex int64 = -1
```

#### Case 5
```
alignment := quaddingLeft
```

The zero value is not clear here. The second example you mentioned does not pass golint and the third uses a cast (an avoidable one).

#### Case 6
```
var ty float64
if condition {
   ty += 2.0
}
```

Simple number type, zero value is obvious.

#### Case 7
```
var isMultiline bool
if condition {
        isMultiline = true
}
```

Again, zero value is obvious. No need to specify it.

#### Case 8
```
isMultiline := true   
if condition {
        isMultiline = false
}
```

Not the zero value. Also golint complains about the other option you mentioned.

#### Conclusion

There are times when golint is somewhat annoying. However, I like that it forces everyone to
write code in the same fashion. Moreover, it is used to test PRs already.

It is never OK to have multiple styles of coding in the same project. Makes things harder to read, understand and further develop.

**Comment by gunnsth** [comment]
The Go Programming Language by Alan A. A. Donovan · Brian W.Kernighan states

> Because of their brevity and flexibility, short variable declarations are used to declare and initialize the majority of local variables. A var declaration tends to be reserved for local variables that need an explicit type that differs from that of the initializer expression, or for when the variable will be assigned a value later and its initial value is unimportant.

Referenced on https://stackoverflow.com/questions/34965414/difference-between-variable-declaration-and-short-variable-declaration-at-lo

I agree with this, preferring the short variable declarations where the initial value matters.

**Comment by gunnsth** [comment]
After looking into the code of golang standard libraries and some other, there is no formal convention.
The style philosophy of UniDoc is to strive for simplicity and clarity. Thus, I have come up with the following proposal for guidelines.

It does assume a knowledge of type inference as per https://tour.golang.org/basics/14  (for int, float64).

Any feedback is appreciated.

# Proposal

When declaring and initializing variables, follow the convention of declaring what matters, e.g.
make the value and type explicit if it matters.

i) If the initial value matters, make it explicit
```go
i := 0
```
ii) If the type matters, make it explicit
```go
var offset uint64
```
iii) If both initial value and type matters, make both explicit (except if obvious: bool, string, int, float64)
```go
offset := uint64(0)
useX := false
```
Cases where it is obvious (type inference)
```go
pi := 3.14  // float64
i := 0 // int
str := "string of runes" // string
useBorders := false // bool
```

iv) If the initial value does not matter declare using `var`.
```go
var i int
```

v) When declaring multiple variables that are related, enclose within a var block.  See also
https://golang.org/doc/effective_go.html#commentary

vi) When declaring empty slices, prefer
```go
var t []string
```
over 
```go
t := []string{}
```
as per https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices


# Examples

1. Iterator - initial value matters.
```go
for i := 0; i < 20; i++ { ... }
```

2. Default value - can change based on logic - initial value matters, type matters, float64 - inferred.
```go
tx := 2.0 // Default offset.
if condition {
    tx += 1.0
}
```

3. Variable declaration where initial value does not matter.
```go
var alignment quadding
if condition {
   alignment = quaddingLeft
} else {
  alignment = quaddingRight
}
```
although this could be better written as
```go
alignment := quaddingRight
if condition {
  alignment = quaddingLeft
}
```

**Comment by gunnsth** [comment]
Updated in wiki
https://github.com/unidoc/unidoc/wiki/UniDoc-Developer-Guide#17-variable-declarations

Closing.

**Comment by dennwc** [comment]
@gunnsth Why the case for maps is different from slices?

> otherwise prefer
> ```golang
>   m := map[x]y{}
> ```
> over
> ```golang
>   m := make(map[x]y)
> ```

Should be the opposite. `make` also makes it clear that map is a reference type, comparing to slices that are just headers.

**Comment by gunnsth** [comment]
The reason was simply that the former style is abundant in unidoc and it does not seem to have any functional difference.  I am happy to reconsider as I agree that the latter syntax seems more consistent with other recommendations. The suggestion will be to prefer this syntax in new code and when rewriting/refactoring.
