### ISSUE TITLE
Decrypting PDF's returns true for any password

### ISSUE THREAD

**Issue by camdenorrb** [unidoc/unidoc#50]
`bool, err := pdfReader.Decrypt([]byte(""))`

No matter what password I supply to that, it returns true and no error. I am testing this on the PDF 1.4 file format.

**Comment by gunnsth** [comment]
Are you on the master branch or v2?

Can you supply a PDF for testing?

**Comment by camdenorrb** [comment]
Here is a test PDF, the password is "hello" without the quotes of course. The PDF is 1.5, but appears to be experiencing the same issue. 

As for the master or v2 branch, I just did `go get github.com/unidoc/unidoc` so which ever one that gets you.

[hello-world.pdf](https://github.com/unidoc/unidoc/files/1006023/hello-world.pdf)

**Comment by gunnsth** [comment]
OK.  That would be the master branch then (version 1).  We will soon be releasing version 2 which has multiple improvements.

This file does not have an opening password. Thus any reader can decrypt it and fully access the contents.

There are two kinds of PDF passwords: 
1. The user password (or opening password), if set, is what you need to provide in order to open a PDF. If this is set, all streams and strings in the document are encrypted and there is no way to access the contents without it.

2. The owner password, if set, controls permissions, such as printing, editing, extracting, commenting, etc.  This could be said to be a "fake" protection, since it is up to the conformant reader to make sure that those permissions are regarded.  In a way it could be said to provide a false sense of security.

The Decrypt() function in unidoc is only authenticating the owner password.  If we can pass that step (in this case an empty string ""), we can access the entire document contents.

**Comment by camdenorrb** [comment]
Although it's considered false sense of security, is there still a way to check if it was decrypted correctly, with the right password?

**Comment by gunnsth** [comment]
Well, this document for example is decrypted correctly with the user opening password (empty string "").  The step of authenticating the owner password ("hello") is not used for decryption.
We do have functionality for authenticating the owner password within unidoc, but those functions are not exported as it is not necessary for working with the file.

May I ask why you want to validate the owner password?  Typically, when we find convincing use cases, we consider exposing the needed functions.

**Comment by camdenorrb** [comment]
I was hoping to use it for validity sake, when having a fully fledged API usually having these functions exposed is better anyways. I was hoping on actually respecting the fallacy based rules it provides.

**Comment by gunnsth** [comment]
OK.  I can understand that and agree with you in principle.  The Decrypt() function is intended to quickly give access to parsing and working with the PDF file contents.

I think adding an Authenticate() method for validating user and owner password as well as returning the intended access permissions would be useful.

I have created a feature/enhancement ticket for this:
https://github.com/unidoc/unidoc/issues/51

Please close the ticket if you agree with this.
Best,
Gus

**Comment by camdenorrb** [comment]
Sounds wonderful! Thank you so much for your time :3

**Comment by gunnsth** [comment]
No problem, thanks for your valuable input!
